INX Future Inc. Employee Performance Analysis

Employee Performance Prediction

This notebook uses the Gradient Boosting classification model to predict employee performance ratings based on employee realted factors.Gradient Boosting model was selected beacause it achieved the highest performance during model evaluation with an accuracy 93.75%.The prediction uses employee information as input and generates a predicted performance rating.

**Import Libraries**

The required libraries are imported to load the trained model,scaler and feature information and also to prepare employee data for prediction.

In [81]:
import pandas as pd
import numpy as np
import joblib

In [82]:
model = joblib.load('gradient_boosting_model (3).pkl')
scaler = joblib.load('scaler (1).pkl')
model_features = joblib.load('model_features.pkl')

print("Model loaded successfully.")
print("Scaler loaded successfully.")
print("Number of model features:", len(model_features))

Model loaded successfully.
Scaler loaded successfully.
Number of model features: 53

**Loading the employee Dataset**

The original employee performance dataset is loaded so as to provide the information required for making predictions.

In [83]:
df = pd.read_excel("/content/INX_Future_Inc_Employee_Performance.xlsx")

In [84]:
df.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

In [85]:
print("Dataset shape:", df.shape)

Dataset shape: (1200, 28)

This is just to confirm that the prediction notebook is working with the same dataset used during model training

**Employee Input**

This is an example of an employee's profile using the same features that were used to train the model. The employee's information is processed in the same way as the training data before making a prediction.

In [86]:
df.columns.tolist()

['EmpNumber',
 'Age',
 'Gender',
 'EducationBackground',
 'MaritalStatus',
 'EmpDepartment',
 'EmpJobRole',
 'BusinessTravelFrequency',
 'DistanceFromHome',
 'EmpEducationLevel',
 'EmpEnvironmentSatisfaction',
 'EmpHourlyRate',
 'EmpJobInvolvement',
 'EmpJobLevel',
 'EmpJobSatisfaction',
 'NumCompaniesWorked',
 'OverTime',
 'EmpLastSalaryHikePercent',
 'EmpRelationshipSatisfaction',
 'TotalWorkExperienceInYears',
 'TrainingTimesLastYear',
 'EmpWorkLifeBalance',
 'ExperienceYearsAtThisCompany',
 'ExperienceYearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'Attrition',
 'PerformanceRating']

In [87]:
employee = pd.DataFrame({
    'Age': [30],
    'Gender': ['Male'],
    'EducationBackground': ['Life Sciences'],
    'MaritalStatus': ['Single'],
    'EmpDepartment': ['Development'],
    'EmpJobRole': ['Developer'],
    'BusinessTravelFrequency': ['Travel_Rarely'],
    'DistanceFromHome': [5],
    'EmpEducationLevel': [3],
    'EmpEnvironmentSatisfaction': [4],
    'EmpHourlyRate': [75],
    'EmpJobInvolvement': [3],
    'EmpJobLevel': [2],
    'EmpJobSatisfaction': [4],
    'NumCompaniesWorked': [2],
    'OverTime': ['No'],
    'EmpLastSalaryHikePercent': [15],
    'EmpRelationshipSatisfaction': [3],
    'TotalWorkExperienceInYears': [6],
    'TrainingTimesLastYear': [3],
    'EmpWorkLifeBalance': [3],
    'ExperienceYearsAtThisCompany': [4],
    'ExperienceYearsInCurrentRole': [2],
    'YearsSinceLastPromotion': [1],
    'YearsWithCurrManager': [2],
    'Attrition': ['No']
})

employee

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,...,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,30,Male,Life Sciences,Single,Development,Developer,Travel_Rarely,5,3,4,...,15,3,6,3,3,4,2,1,2,No

The employee's profile is using the original employee attributes.The input is then transformed using the same encoding and scaling procedures applied during model training.

**Prepare Employee Input**

The categorical variables in the employee input is converted into numerical values using one hot encoding. The same encoding approach used during the model training is applied to ensure that the input matches the format expected by the trained model.

In [88]:
employee_encoded = pd.get_dummies(
    employee,
    drop_first=True
)

employee_encoded

,Age,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,30,5,3,4,75,3,2,4,2,15,3,6,3,3,4,2,1,2

In [89]:
employee_encoded = employee_encoded.reindex(
    columns=model_features,
    fill_value=0
)

employee_encoded

,Age,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,EmpLastSalaryHikePercent,...,EmpJobRole_Sales Executive,EmpJobRole_Sales Representative,EmpJobRole_Senior Developer,EmpJobRole_Senior Manager R&D,EmpJobRole_Technical Architect,EmpJobRole_Technical Lead,BusinessTravelFrequency_Travel_Frequently,BusinessTravelFrequency_Travel_Rarely,OverTime_Yes,Attrition_Yes
0,30,5,3,4,75,3,2,4,2,15,...,0,0,0,0,0,0,0,0,0,0

In [90]:
employee_scaled = scaler.transform(employee_encoded)

**Predict Employee Performance**

The prepared employee data is now passed to the trained Gradient Boosting model to predict the employee's performance rating.

In [93]:
prediction = model.predict(employee_encoded)

print("Predicted Performance Rating:", prediction[0])

Predicted Performance Rating: 3